image_width: 80
image_height: 60
camera_name: lepton_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [84.7, 0., 40.0, 0., 84.7, 30.0, 0., 0., 1.]
# after here inaccurate
distortion_model: plumb_bob 
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0, 0, 0, 0, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [84.7, 0., 40.0, 0., 0., 84.7, 30.0, 0., 0., 0., 1., 0.]
