on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: catkin_lint

    steps:
      - name: Setup OS
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
      - name: Setup Git
        run: |
          sudo apt-get install -y git
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: catkin lint setup
        run: |
          sudo apt-get install -y -q python3-pip
          sudo pip3 install catkin_lint rosdep
          sudo rosdep init
          rosdep update
      - name: catkin lint test
        run: |
          ROS_DISTRO=melodic catkin_lint --resolve-env --strict $PWD
